-- ============================================================
-- Shared-DB Multi-Tenancy: add school_id to tenant tables
-- Backward compatible: DEFAULT 1 => existing rows belong to school #1.
-- Review the GLOBAL exclusions at the bottom before running.
-- Generated for 183 tenant tables (8 kept global).
-- ============================================================

ALTER TABLE `addon_versions` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `addon_versions` ADD INDEX `idx_addon_versions_school` (`school_id`);
ALTER TABLE `addons` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `addons` ADD INDEX `idx_addons_school` (`school_id`);
ALTER TABLE `alumni_events` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `alumni_events` ADD INDEX `idx_alumni_events_school` (`school_id`);
ALTER TABLE `alumni_students` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `alumni_students` ADD INDEX `idx_alumni_students_school` (`school_id`);
ALTER TABLE `annual_calendar` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `annual_calendar` ADD INDEX `idx_annual_calendar_school` (`school_id`);
ALTER TABLE `attendence_type` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `attendence_type` ADD INDEX `idx_attendence_type_school` (`school_id`);
ALTER TABLE `book_issues` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `book_issues` ADD INDEX `idx_book_issues_school` (`school_id`);
ALTER TABLE `books` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `books` ADD INDEX `idx_books_school` (`school_id`);
ALTER TABLE `captcha` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `captcha` ADD INDEX `idx_captcha_school` (`school_id`);
ALTER TABLE `categories` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `categories` ADD INDEX `idx_categories_school` (`school_id`);
ALTER TABLE `certificates` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `certificates` ADD INDEX `idx_certificates_school` (`school_id`);
ALTER TABLE `chat_connections` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `chat_connections` ADD INDEX `idx_chat_connections_school` (`school_id`);
ALTER TABLE `chat_messages` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `chat_messages` ADD INDEX `idx_chat_messages_school` (`school_id`);
ALTER TABLE `chat_users` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `chat_users` ADD INDEX `idx_chat_users_school` (`school_id`);
ALTER TABLE `class_section_times` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `class_section_times` ADD INDEX `idx_class_section_times_school` (`school_id`);
ALTER TABLE `class_sections` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `class_sections` ADD INDEX `idx_class_sections_school` (`school_id`);
ALTER TABLE `class_teacher` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `class_teacher` ADD INDEX `idx_class_teacher_school` (`school_id`);
ALTER TABLE `classes` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `classes` ADD INDEX `idx_classes_school` (`school_id`);
ALTER TABLE `complaint` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `complaint` ADD INDEX `idx_complaint_school` (`school_id`);
ALTER TABLE `complaint_type` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `complaint_type` ADD INDEX `idx_complaint_type_school` (`school_id`);
ALTER TABLE `content_for` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `content_for` ADD INDEX `idx_content_for_school` (`school_id`);
ALTER TABLE `content_types` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `content_types` ADD INDEX `idx_content_types_school` (`school_id`);
ALTER TABLE `contents` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `contents` ADD INDEX `idx_contents_school` (`school_id`);
ALTER TABLE `cumulative_fine` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `cumulative_fine` ADD INDEX `idx_cumulative_fine_school` (`school_id`);
ALTER TABLE `currencies` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `currencies` ADD INDEX `idx_currencies_school` (`school_id`);
ALTER TABLE `custom_field_values` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `custom_field_values` ADD INDEX `idx_custom_field_values_school` (`school_id`);
ALTER TABLE `custom_fields` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `custom_fields` ADD INDEX `idx_custom_fields_school` (`school_id`);
ALTER TABLE `daily_assignment` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `daily_assignment` ADD INDEX `idx_daily_assignment_school` (`school_id`);
ALTER TABLE `department` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `department` ADD INDEX `idx_department_school` (`school_id`);
ALTER TABLE `disable_reason` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `disable_reason` ADD INDEX `idx_disable_reason_school` (`school_id`);
ALTER TABLE `dispatch_receive` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `dispatch_receive` ADD INDEX `idx_dispatch_receive_school` (`school_id`);
ALTER TABLE `email_attachments` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `email_attachments` ADD INDEX `idx_email_attachments_school` (`school_id`);
ALTER TABLE `email_template` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `email_template` ADD INDEX `idx_email_template_school` (`school_id`);
ALTER TABLE `email_template_attachment` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `email_template_attachment` ADD INDEX `idx_email_template_attachment_school` (`school_id`);
ALTER TABLE `enquiry` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `enquiry` ADD INDEX `idx_enquiry_school` (`school_id`);
ALTER TABLE `enquiry_type` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `enquiry_type` ADD INDEX `idx_enquiry_type_school` (`school_id`);
ALTER TABLE `events` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `events` ADD INDEX `idx_events_school` (`school_id`);
ALTER TABLE `exam_group_class_batch_exam_students` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_group_class_batch_exam_students` ADD INDEX `idx_exam_group_class_batch_exam_students_school` (`school_id`);
ALTER TABLE `exam_group_class_batch_exam_subjects` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_group_class_batch_exam_subjects` ADD INDEX `idx_exam_group_class_batch_exam_subjects_school` (`school_id`);
ALTER TABLE `exam_group_class_batch_exams` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_group_class_batch_exams` ADD INDEX `idx_exam_group_class_batch_exams_school` (`school_id`);
ALTER TABLE `exam_group_exam_connections` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_group_exam_connections` ADD INDEX `idx_exam_group_exam_connections_school` (`school_id`);
ALTER TABLE `exam_group_exam_results` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_group_exam_results` ADD INDEX `idx_exam_group_exam_results_school` (`school_id`);
ALTER TABLE `exam_group_students` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_group_students` ADD INDEX `idx_exam_group_students_school` (`school_id`);
ALTER TABLE `exam_groups` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_groups` ADD INDEX `idx_exam_groups_school` (`school_id`);
ALTER TABLE `exam_schedules` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exam_schedules` ADD INDEX `idx_exam_schedules_school` (`school_id`);
ALTER TABLE `exams` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `exams` ADD INDEX `idx_exams_school` (`school_id`);
ALTER TABLE `expense_head` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `expense_head` ADD INDEX `idx_expense_head_school` (`school_id`);
ALTER TABLE `expenses` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `expenses` ADD INDEX `idx_expenses_school` (`school_id`);
ALTER TABLE `fee_groups` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `fee_groups` ADD INDEX `idx_fee_groups_school` (`school_id`);
ALTER TABLE `fee_groups_feetype` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `fee_groups_feetype` ADD INDEX `idx_fee_groups_feetype_school` (`school_id`);
ALTER TABLE `fee_receipt_no` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `fee_receipt_no` ADD INDEX `idx_fee_receipt_no_school` (`school_id`);
ALTER TABLE `fee_session_groups` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `fee_session_groups` ADD INDEX `idx_fee_session_groups_school` (`school_id`);
ALTER TABLE `feemasters` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `feemasters` ADD INDEX `idx_feemasters_school` (`school_id`);
ALTER TABLE `fees_discounts` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `fees_discounts` ADD INDEX `idx_fees_discounts_school` (`school_id`);
ALTER TABLE `fees_reminder` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `fees_reminder` ADD INDEX `idx_fees_reminder_school` (`school_id`);
ALTER TABLE `feetype` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `feetype` ADD INDEX `idx_feetype_school` (`school_id`);
ALTER TABLE `filetypes` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `filetypes` ADD INDEX `idx_filetypes_school` (`school_id`);
ALTER TABLE `follow_up` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `follow_up` ADD INDEX `idx_follow_up_school` (`school_id`);
ALTER TABLE `front_cms_media_gallery` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_media_gallery` ADD INDEX `idx_front_cms_media_gallery_school` (`school_id`);
ALTER TABLE `front_cms_menu_items` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_menu_items` ADD INDEX `idx_front_cms_menu_items_school` (`school_id`);
ALTER TABLE `front_cms_menus` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_menus` ADD INDEX `idx_front_cms_menus_school` (`school_id`);
ALTER TABLE `front_cms_page_contents` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_page_contents` ADD INDEX `idx_front_cms_page_contents_school` (`school_id`);
ALTER TABLE `front_cms_pages` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_pages` ADD INDEX `idx_front_cms_pages_school` (`school_id`);
ALTER TABLE `front_cms_program_photos` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_program_photos` ADD INDEX `idx_front_cms_program_photos_school` (`school_id`);
ALTER TABLE `front_cms_programs` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_programs` ADD INDEX `idx_front_cms_programs_school` (`school_id`);
ALTER TABLE `front_cms_settings` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `front_cms_settings` ADD INDEX `idx_front_cms_settings_school` (`school_id`);
ALTER TABLE `gateway_ins` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `gateway_ins` ADD INDEX `idx_gateway_ins_school` (`school_id`);
ALTER TABLE `gateway_ins_response` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `gateway_ins_response` ADD INDEX `idx_gateway_ins_response_school` (`school_id`);
ALTER TABLE `general_calls` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `general_calls` ADD INDEX `idx_general_calls_school` (`school_id`);
ALTER TABLE `grades` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `grades` ADD INDEX `idx_grades_school` (`school_id`);
ALTER TABLE `holiday_type` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `holiday_type` ADD INDEX `idx_holiday_type_school` (`school_id`);
ALTER TABLE `homework` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `homework` ADD INDEX `idx_homework_school` (`school_id`);
ALTER TABLE `homework_evaluation` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `homework_evaluation` ADD INDEX `idx_homework_evaluation_school` (`school_id`);
ALTER TABLE `hostel` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `hostel` ADD INDEX `idx_hostel_school` (`school_id`);
ALTER TABLE `hostel_rooms` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `hostel_rooms` ADD INDEX `idx_hostel_rooms_school` (`school_id`);
ALTER TABLE `id_card` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `id_card` ADD INDEX `idx_id_card_school` (`school_id`);
ALTER TABLE `income` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `income` ADD INDEX `idx_income_school` (`school_id`);
ALTER TABLE `income_head` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `income_head` ADD INDEX `idx_income_head_school` (`school_id`);
ALTER TABLE `item` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `item` ADD INDEX `idx_item_school` (`school_id`);
ALTER TABLE `item_category` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `item_category` ADD INDEX `idx_item_category_school` (`school_id`);
ALTER TABLE `item_issue` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `item_issue` ADD INDEX `idx_item_issue_school` (`school_id`);
ALTER TABLE `item_stock` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `item_stock` ADD INDEX `idx_item_stock_school` (`school_id`);
ALTER TABLE `item_store` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `item_store` ADD INDEX `idx_item_store_school` (`school_id`);
ALTER TABLE `item_supplier` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `item_supplier` ADD INDEX `idx_item_supplier_school` (`school_id`);
ALTER TABLE `leave_types` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `leave_types` ADD INDEX `idx_leave_types_school` (`school_id`);
ALTER TABLE `lesson` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `lesson` ADD INDEX `idx_lesson_school` (`school_id`);
ALTER TABLE `lesson_plan_forum` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `lesson_plan_forum` ADD INDEX `idx_lesson_plan_forum_school` (`school_id`);
ALTER TABLE `libarary_members` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `libarary_members` ADD INDEX `idx_libarary_members_school` (`school_id`);
ALTER TABLE `logs` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `logs` ADD INDEX `idx_logs_school` (`school_id`);
ALTER TABLE `mark_divisions` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `mark_divisions` ADD INDEX `idx_mark_divisions_school` (`school_id`);
ALTER TABLE `messages` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `messages` ADD INDEX `idx_messages_school` (`school_id`);
ALTER TABLE `notification_roles` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `notification_roles` ADD INDEX `idx_notification_roles_school` (`school_id`);
ALTER TABLE `notification_setting` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `notification_setting` ADD INDEX `idx_notification_setting_school` (`school_id`);
ALTER TABLE `offline_fees_payments` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `offline_fees_payments` ADD INDEX `idx_offline_fees_payments_school` (`school_id`);
ALTER TABLE `online_admission_custom_field_value` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `online_admission_custom_field_value` ADD INDEX `idx_online_admission_custom_field_value_school` (`school_id`);
ALTER TABLE `online_admission_fields` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `online_admission_fields` ADD INDEX `idx_online_admission_fields_school` (`school_id`);
ALTER TABLE `online_admission_payment` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `online_admission_payment` ADD INDEX `idx_online_admission_payment_school` (`school_id`);
ALTER TABLE `online_admissions` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `online_admissions` ADD INDEX `idx_online_admissions_school` (`school_id`);
ALTER TABLE `onlineexam` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `onlineexam` ADD INDEX `idx_onlineexam_school` (`school_id`);
ALTER TABLE `onlineexam_attempts` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `onlineexam_attempts` ADD INDEX `idx_onlineexam_attempts_school` (`school_id`);
ALTER TABLE `onlineexam_questions` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `onlineexam_questions` ADD INDEX `idx_onlineexam_questions_school` (`school_id`);
ALTER TABLE `onlineexam_student_results` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `onlineexam_student_results` ADD INDEX `idx_onlineexam_student_results_school` (`school_id`);
ALTER TABLE `onlineexam_students` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `onlineexam_students` ADD INDEX `idx_onlineexam_students_school` (`school_id`);
ALTER TABLE `payment_settings` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `payment_settings` ADD INDEX `idx_payment_settings_school` (`school_id`);
ALTER TABLE `payslip_allowance` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `payslip_allowance` ADD INDEX `idx_payslip_allowance_school` (`school_id`);
ALTER TABLE `permission_student` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `permission_student` ADD INDEX `idx_permission_student_school` (`school_id`);
ALTER TABLE `pickup_point` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `pickup_point` ADD INDEX `idx_pickup_point_school` (`school_id`);
ALTER TABLE `print_headerfooter` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `print_headerfooter` ADD INDEX `idx_print_headerfooter_school` (`school_id`);
ALTER TABLE `questions` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `questions` ADD INDEX `idx_questions_school` (`school_id`);
ALTER TABLE `read_notification` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `read_notification` ADD INDEX `idx_read_notification_school` (`school_id`);
ALTER TABLE `reference` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `reference` ADD INDEX `idx_reference_school` (`school_id`);
ALTER TABLE `resume_additional_fields_settings` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `resume_additional_fields_settings` ADD INDEX `idx_resume_additional_fields_settings_school` (`school_id`);
ALTER TABLE `resume_settings_fields` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `resume_settings_fields` ADD INDEX `idx_resume_settings_fields_school` (`school_id`);
ALTER TABLE `roles` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `roles` ADD INDEX `idx_roles_school` (`school_id`);
ALTER TABLE `room_types` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `room_types` ADD INDEX `idx_room_types_school` (`school_id`);
ALTER TABLE `route_pickup_point` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `route_pickup_point` ADD INDEX `idx_route_pickup_point_school` (`school_id`);
ALTER TABLE `school_houses` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `school_houses` ADD INDEX `idx_school_houses_school` (`school_id`);
ALTER TABLE `sections` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `sections` ADD INDEX `idx_sections_school` (`school_id`);
ALTER TABLE `send_notification` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `send_notification` ADD INDEX `idx_send_notification_school` (`school_id`);
ALTER TABLE `share_content_for` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `share_content_for` ADD INDEX `idx_share_content_for_school` (`school_id`);
ALTER TABLE `share_contents` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `share_contents` ADD INDEX `idx_share_contents_school` (`school_id`);
ALTER TABLE `share_upload_contents` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `share_upload_contents` ADD INDEX `idx_share_upload_contents_school` (`school_id`);
ALTER TABLE `sidebar_menus` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `sidebar_menus` ADD INDEX `idx_sidebar_menus_school` (`school_id`);
ALTER TABLE `sidebar_sub_menus` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `sidebar_sub_menus` ADD INDEX `idx_sidebar_sub_menus_school` (`school_id`);
ALTER TABLE `sms_config` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `sms_config` ADD INDEX `idx_sms_config_school` (`school_id`);
ALTER TABLE `sms_template` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `sms_template` ADD INDEX `idx_sms_template_school` (`school_id`);
ALTER TABLE `source` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `source` ADD INDEX `idx_source_school` (`school_id`);
ALTER TABLE `staff` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff` ADD INDEX `idx_staff_school` (`school_id`);
ALTER TABLE `staff_attendance` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_attendance` ADD INDEX `idx_staff_attendance_school` (`school_id`);
ALTER TABLE `staff_attendance_type` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_attendance_type` ADD INDEX `idx_staff_attendance_type_school` (`school_id`);
ALTER TABLE `staff_attendence_schedules` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_attendence_schedules` ADD INDEX `idx_staff_attendence_schedules_school` (`school_id`);
ALTER TABLE `staff_designation` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_designation` ADD INDEX `idx_staff_designation_school` (`school_id`);
ALTER TABLE `staff_id_card` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_id_card` ADD INDEX `idx_staff_id_card_school` (`school_id`);
ALTER TABLE `staff_leave_details` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_leave_details` ADD INDEX `idx_staff_leave_details_school` (`school_id`);
ALTER TABLE `staff_leave_request` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_leave_request` ADD INDEX `idx_staff_leave_request_school` (`school_id`);
ALTER TABLE `staff_payroll` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_payroll` ADD INDEX `idx_staff_payroll_school` (`school_id`);
ALTER TABLE `staff_payslip` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_payslip` ADD INDEX `idx_staff_payslip_school` (`school_id`);
ALTER TABLE `staff_rating` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_rating` ADD INDEX `idx_staff_rating_school` (`school_id`);
ALTER TABLE `staff_roles` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_roles` ADD INDEX `idx_staff_roles_school` (`school_id`);
ALTER TABLE `staff_timeline` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `staff_timeline` ADD INDEX `idx_staff_timeline_school` (`school_id`);
ALTER TABLE `student_applied_discounts` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_applied_discounts` ADD INDEX `idx_student_applied_discounts_school` (`school_id`);
ALTER TABLE `student_applyleave` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_applyleave` ADD INDEX `idx_student_applyleave_school` (`school_id`);
ALTER TABLE `student_attendence_schedules` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_attendence_schedules` ADD INDEX `idx_student_attendence_schedules_school` (`school_id`);
ALTER TABLE `student_attendences` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_attendences` ADD INDEX `idx_student_attendences_school` (`school_id`);
ALTER TABLE `student_dashboard_settings` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_dashboard_settings` ADD INDEX `idx_student_dashboard_settings_school` (`school_id`);
ALTER TABLE `student_doc` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_doc` ADD INDEX `idx_student_doc_school` (`school_id`);
ALTER TABLE `student_edit_fields` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_edit_fields` ADD INDEX `idx_student_edit_fields_school` (`school_id`);
ALTER TABLE `student_educational_details` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_educational_details` ADD INDEX `idx_student_educational_details_school` (`school_id`);
ALTER TABLE `student_fees` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_fees` ADD INDEX `idx_student_fees_school` (`school_id`);
ALTER TABLE `student_fees_deposite` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_fees_deposite` ADD INDEX `idx_student_fees_deposite_school` (`school_id`);
ALTER TABLE `student_fees_discounts` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_fees_discounts` ADD INDEX `idx_student_fees_discounts_school` (`school_id`);
ALTER TABLE `student_fees_master` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_fees_master` ADD INDEX `idx_student_fees_master_school` (`school_id`);
ALTER TABLE `student_fees_processing` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_fees_processing` ADD INDEX `idx_student_fees_processing_school` (`school_id`);
ALTER TABLE `student_refrence` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_refrence` ADD INDEX `idx_student_refrence_school` (`school_id`);
ALTER TABLE `student_session` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_session` ADD INDEX `idx_student_session_school` (`school_id`);
ALTER TABLE `student_skills_detail` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_skills_detail` ADD INDEX `idx_student_skills_detail_school` (`school_id`);
ALTER TABLE `student_subject_attendances` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_subject_attendances` ADD INDEX `idx_student_subject_attendances_school` (`school_id`);
ALTER TABLE `student_timeline` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_timeline` ADD INDEX `idx_student_timeline_school` (`school_id`);
ALTER TABLE `student_transport_fees` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_transport_fees` ADD INDEX `idx_student_transport_fees_school` (`school_id`);
ALTER TABLE `student_work_experience` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `student_work_experience` ADD INDEX `idx_student_work_experience_school` (`school_id`);
ALTER TABLE `students` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `students` ADD INDEX `idx_students_school` (`school_id`);
ALTER TABLE `subject_group_class_sections` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `subject_group_class_sections` ADD INDEX `idx_subject_group_class_sections_school` (`school_id`);
ALTER TABLE `subject_group_subjects` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `subject_group_subjects` ADD INDEX `idx_subject_group_subjects_school` (`school_id`);
ALTER TABLE `subject_groups` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `subject_groups` ADD INDEX `idx_subject_groups_school` (`school_id`);
ALTER TABLE `subject_syllabus` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `subject_syllabus` ADD INDEX `idx_subject_syllabus_school` (`school_id`);
ALTER TABLE `subject_timetable` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `subject_timetable` ADD INDEX `idx_subject_timetable_school` (`school_id`);
ALTER TABLE `subjects` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `subjects` ADD INDEX `idx_subjects_school` (`school_id`);
ALTER TABLE `submit_assignment` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `submit_assignment` ADD INDEX `idx_submit_assignment_school` (`school_id`);
ALTER TABLE `template_admitcards` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `template_admitcards` ADD INDEX `idx_template_admitcards_school` (`school_id`);
ALTER TABLE `template_marksheets` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `template_marksheets` ADD INDEX `idx_template_marksheets_school` (`school_id`);
ALTER TABLE `topic` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `topic` ADD INDEX `idx_topic_school` (`school_id`);
ALTER TABLE `transport_feemaster` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `transport_feemaster` ADD INDEX `idx_transport_feemaster_school` (`school_id`);
ALTER TABLE `transport_route` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `transport_route` ADD INDEX `idx_transport_route_school` (`school_id`);
ALTER TABLE `upload_contents` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `upload_contents` ADD INDEX `idx_upload_contents_school` (`school_id`);
ALTER TABLE `userlog` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `userlog` ADD INDEX `idx_userlog_school` (`school_id`);
ALTER TABLE `users` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `users` ADD INDEX `idx_users_school` (`school_id`);
ALTER TABLE `users_authentication` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `users_authentication` ADD INDEX `idx_users_authentication_school` (`school_id`);
ALTER TABLE `vehicle_routes` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `vehicle_routes` ADD INDEX `idx_vehicle_routes_school` (`school_id`);
ALTER TABLE `vehicles` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `vehicles` ADD INDEX `idx_vehicles_school` (`school_id`);
ALTER TABLE `video_tutorial` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `video_tutorial` ADD INDEX `idx_video_tutorial_school` (`school_id`);
ALTER TABLE `video_tutorial_class_sections` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `video_tutorial_class_sections` ADD INDEX `idx_video_tutorial_class_sections_school` (`school_id`);
ALTER TABLE `visitors_book` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `visitors_book` ADD INDEX `idx_visitors_book_school` (`school_id`);
ALTER TABLE `visitors_purpose` ADD COLUMN `school_id` INT NOT NULL DEFAULT 1;
ALTER TABLE `visitors_purpose` ADD INDEX `idx_visitors_purpose_school` (`school_id`);

-- ---- GLOBAL tables (intentionally NOT scoped) ----
-- global: email_config
-- global: languages
-- global: migrations
-- global: permission_category
-- global: permission_group
-- global: roles_permissions
-- global: sch_settings
-- global: sessions
